name: CI

on: [push]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: install-tools
        uses: ./.github/workflows/install-tools

      - name: Run tests
        shell: bash
        run: pnpm test:unit

  e2e-tests:
    name: Run E2E tests
    runs-on: ubuntu-latest
    environment: e2e
    env:
      MAINNET_RPC: ${{ secrets.MAINNET_RPC || vars.MAINNET_RPC }}
      SEPOLIA_RPC: ${{ secrets.SEPOLIA_RPC || vars.SEPOLIA_RPC }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: install-tools
        uses: ./.github/workflows/install-tools

      - name: Run E2E tests
        run: pnpm test:integration

  lint:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@v5
      - name: install-tools
        uses: ./.github/workflows/install-tools

      - name: Run Forge formatter and Solhint
        run: pnpm lint:check

      - name: Install and run Bulloak
        uses: smol-ninja/bulloak-toolchain@v2
        with:
          test-dir: 'test/unit'
